# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rentCar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rentCar

  pod 'Toaster', '~> 2.1.1'
  pod 'SnapKit', '~> 4.2.0'
  pod 'Kingfisher', '~> 4.10.1'
  pod 'FSPagerView', '~> 0.8.2'
  pod 'MJRefresh'
  pod 'Moya', '~> 12.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'UITextView+Placeholder'

end
